[providers]
# MusicBrainz is always enabled
musicbrainz_rate_limit = 1.0  # requests per second

[providers.discogs]
enabled = true
token = "YOUR_DISCOGS_TOKEN"

[providers.spotify]
enabled = false
client_id = ""
client_secret = ""

[providers.itunes]
enabled = true

[search]
auto_search = true
max_results = 5
min_score = 0.85
