[package]
name = "music-dlp-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.25.0"
crossterm = "0.27.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
thiserror = "1.0"
